import { ListFlagsTypes } from '@/types/listFlags.types'

export const mockProjectFlags: ListFlagsTypes = {
  _links: {
    self: {
      href: '/api/v2/flags/default?d=1695318110107&summary=true',
      type: 'application/json',
    },
  },
  items: [
    {
      _links: {
        parent: { href: '/api/v2/flags/default', type: 'application/json' },
        self: {
          href: '/api/v2/flags/default/my-flag',
          type: 'application/json',
        },
      },
      _maintainer: {
        _id: '650367bb14803112809723fb',
        _links: {
          self: {
            href: '/api/v2/members/650367bb14803112809723fb',
            type: 'application/json',
          },
        },
        email: 'mikedidomizio@gmail.com',
        firstName: 'Mike',
        lastName: 'DiDomizio',
        role: 'owner',
      },
      _version: 9,
      archived: false,
      clientSideAvailability: {
        usingEnvironmentId: false,
        usingMobileKey: false,
      },
      creationDate: 1694721999396,
      customProperties: {},
      defaults: { offVariation: 1, onVariation: 0 },
      description: 'This is my description',
      environments: {
        production: {
          _environmentName: 'Production',
          _site: {
            href: '/default/production/features/my-flag',
            type: 'text/html',
          },
          _summary: {
            prerequisites: 0,
            variations: {
              '0': { isFallthrough: true, nullRules: 0, rules: 0, targets: 0 },
              '1': { isOff: true, nullRules: 0, rules: 0, targets: 0 },
            },
          },
          archived: false,
          lastModified: 1694871217848,
          on: true,
          salt: 'cce61c03a54d4b0398576ef0cc9670a4',
          sel: 'a8cc7626c12845e69956d73efd017ba9',
          trackEvents: false,
          trackEventsFallthrough: false,
          version: 20,
        },
        test: {
          _environmentName: 'Test',
          _site: { href: '/default/test/features/my-flag', type: 'text/html' },
          _summary: {
            prerequisites: 0,
            variations: {
              '0': { isFallthrough: true, nullRules: 0, rules: 0, targets: 0 },
              '1': { isOff: true, nullRules: 0, rules: 0, targets: 0 },
            },
          },
          archived: false,
          lastModified: 1695259458637,
          on: false,
          salt: 'c9a9cacb703a4f19a0095f9ed94397bd',
          sel: 'c8ba96a12c254a44b619ac4f27892f34',
          trackEvents: false,
          trackEventsFallthrough: false,
          version: 25,
        },
      },
      experiments: { baselineIdx: 0, items: [] },
      goalIds: [],
      includeInSnippet: false,
      key: 'my-flag',
      kind: 'boolean',
      maintainerId: '650367bb14803112809723fb',
      name: 'my-flag',
      tags: [],
      temporary: true,
      variationJsonSchema: null,
      variations: [
        { _id: '751d7b01-30e8-47b6-aac8-46f599754675', value: true },
        { _id: '8d60b73a-f60c-4e2c-a6b3-b1514e5105b5', value: false },
      ],
    },
    {
      _links: {
        parent: { href: '/api/v2/flags/default', type: 'application/json' },
        self: {
          href: '/api/v2/flags/default/my-flag-2',
          type: 'application/json',
        },
      },
      _maintainer: {
        _id: '650367bb14803112809723fb',
        _links: {
          self: {
            href: '/api/v2/members/650367bb14803112809723fb',
            type: 'application/json',
          },
        },
        email: 'mikedidomizio@gmail.com',
        firstName: 'Mike',
        lastName: 'DiDomizio',
        role: 'owner',
      },
      _version: 12,
      archived: false,
      clientSideAvailability: {
        usingEnvironmentId: false,
        usingMobileKey: false,
      },
      creationDate: 1694816799430,
      customProperties: {},
      defaults: { offVariation: 1, onVariation: 1 },
      description: '',
      environments: {
        production: {
          _environmentName: 'Production',
          _site: {
            href: '/default/production/features/my-flag-2',
            type: 'text/html',
          },
          _summary: {
            prerequisites: 0,
            variations: {
              '0': { isFallthrough: true, nullRules: 0, rules: 0, targets: 0 },
              '1': { isOff: true, nullRules: 0, rules: 0, targets: 0 },
            },
          },
          archived: false,
          lastModified: 1694818772320,
          on: true,
          salt: '988dd0f28dfb4829b94f508cde9943c5',
          sel: 'cf5408f96e174431867cd78146c2041d',
          trackEvents: false,
          trackEventsFallthrough: false,
          version: 3,
        },
        test: {
          _environmentName: 'Test',
          _site: {
            href: '/default/test/features/my-flag-2',
            type: 'text/html',
          },
          _summary: {
            prerequisites: 0,
            variations: {
              '0': { isFallthrough: true, nullRules: 0, rules: 0, targets: 0 },
              '1': { isOff: true, nullRules: 0, rules: 0, targets: 0 },
            },
          },
          archived: false,
          lastModified: 1695258649461,
          on: true,
          salt: '9c6aad8a7e14493fb352bc95abdf37bf',
          sel: 'c3401ea7bbb843d693e26c18cc687df0',
          trackEvents: false,
          trackEventsFallthrough: false,
          version: 47,
        },
      },
      experiments: { baselineIdx: 0, items: [] },
      goalIds: [],
      includeInSnippet: false,
      key: 'my-flag-2',
      kind: 'boolean',
      maintainerId: '650367bb14803112809723fb',
      name: 'my-flag-2',
      tags: [],
      temporary: true,
      variationJsonSchema: null,
      variations: [
        { _id: 'e985f043-2377-4882-923f-65ec1e16207e', value: true },
        { _id: 'ea7613c6-b60a-4353-a7b9-9194a8ec8732', value: false },
      ],
    },
    {
      _links: {
        parent: { href: '/api/v2/flags/default', type: 'application/json' },
        self: {
          href: '/api/v2/flags/default/another-flag',
          type: 'application/json',
        },
      },
      _maintainer: {
        _id: '650367bb14803112809723fb',
        _links: {
          self: {
            href: '/api/v2/members/650367bb14803112809723fb',
            type: 'application/json',
          },
        },
        email: 'mikedidomizio@gmail.com',
        firstName: 'Mike',
        lastName: 'DiDomizio',
        role: 'owner',
      },
      _version: 21,
      archived: false,
      clientSideAvailability: {
        usingEnvironmentId: false,
        usingMobileKey: false,
      },
      creationDate: 1694918015913,
      customProperties: {},
      defaults: { offVariation: 1, onVariation: 0 },
      description: '',
      environments: {
        production: {
          _environmentName: 'Production',
          _site: {
            href: '/default/production/features/another-flag',
            type: 'text/html',
          },
          _summary: {
            prerequisites: 0,
            variations: {
              '0': { isFallthrough: true, nullRules: 0, rules: 0, targets: 0 },
              '1': { isOff: true, nullRules: 0, rules: 0, targets: 0 },
            },
          },
          archived: false,
          lastModified: 1694918015942,
          on: false,
          salt: '12d497690b614ca5848eec1bef272faa',
          sel: '936bc99266f94e8e8452e6fde664a520',
          trackEvents: false,
          trackEventsFallthrough: false,
          version: 1,
        },
        test: {
          _environmentName: 'Test',
          _site: {
            href: '/default/test/features/another-flag',
            type: 'text/html',
          },
          _summary: {
            prerequisites: 0,
            variations: {
              '0': { isFallthrough: true, nullRules: 0, rules: 0, targets: 0 },
              '1': { isOff: true, nullRules: 0, rules: 0, targets: 0 },
            },
          },
          archived: false,
          lastModified: 1695258428532,
          on: true,
          salt: '51a8b5e792544083b5046d0ff6366704',
          sel: '779f1d014c8e454a9e881068e752d54b',
          trackEvents: false,
          trackEventsFallthrough: false,
          version: 34,
        },
      },
      experiments: { baselineIdx: 0, items: [] },
      goalIds: [],
      includeInSnippet: false,
      key: 'another-flag',
      kind: 'boolean',
      maintainerId: '650367bb14803112809723fb',
      name: 'another-flag',
      tags: [],
      temporary: true,
      variationJsonSchema: null,
      variations: [
        { _id: 'fca2b238-26d2-4b2b-be43-a8404a76c36e', value: true },
        { _id: 'd30c770f-4c36-4d43-a902-babbe99c0eab', value: false },
      ],
    },
    {
      _links: {
        parent: { href: '/api/v2/flags/default', type: 'application/json' },
        self: {
          href: '/api/v2/flags/default/another-one',
          type: 'application/json',
        },
      },
      _maintainer: {
        _id: '650367bb14803112809723fb',
        _links: {
          self: {
            href: '/api/v2/members/650367bb14803112809723fb',
            type: 'application/json',
          },
        },
        email: 'mikedidomizio@gmail.com',
        firstName: 'Mike',
        lastName: 'DiDomizio',
        role: 'owner',
      },
      _version: 13,
      archived: false,
      clientSideAvailability: {
        usingEnvironmentId: false,
        usingMobileKey: false,
      },
      creationDate: 1694918029012,
      customProperties: {},
      defaults: { offVariation: 1, onVariation: 0 },
      description: '',
      environments: {
        production: {
          _environmentName: 'Production',
          _site: {
            href: '/default/production/features/another-one',
            type: 'text/html',
          },
          _summary: {
            prerequisites: 0,
            variations: {
              '0': { isFallthrough: true, nullRules: 0, rules: 0, targets: 0 },
              '1': { isOff: true, nullRules: 0, rules: 0, targets: 0 },
            },
          },
          archived: false,
          lastModified: 1694918029037,
          on: false,
          salt: '536e6e10cd224e72afa4ea93a74c8532',
          sel: '117b8bc3399b44d994cd35453e559cbb',
          trackEvents: false,
          trackEventsFallthrough: false,
          version: 1,
        },
        test: {
          _environmentName: 'Test',
          _site: {
            href: '/default/test/features/another-one',
            type: 'text/html',
          },
          _summary: {
            prerequisites: 0,
            variations: {
              '0': { isFallthrough: true, nullRules: 0, rules: 0, targets: 0 },
              '1': { isOff: true, nullRules: 0, rules: 0, targets: 0 },
            },
          },
          archived: false,
          lastModified: 1695255448214,
          on: true,
          salt: 'e8e528c4da0849348d448720b65b1bcb',
          sel: '682965ecb9ea4e2093efb69d15cd96aa',
          trackEvents: false,
          trackEventsFallthrough: false,
          version: 20,
        },
      },
      experiments: { baselineIdx: 0, items: [] },
      goalIds: [],
      includeInSnippet: false,
      key: 'another-one',
      kind: 'boolean',
      maintainerId: '650367bb14803112809723fb',
      name: 'another-one',
      tags: ['tag1', 'tag2', 'tag3'],
      temporary: true,
      variationJsonSchema: null,
      variations: [
        { _id: '9ce577ee-c7d7-47e9-91c8-e9509def1ffa', value: true },
        { _id: 'a2beee86-d673-4ff4-9dfe-19bb1dbe185d', value: false },
      ],
    },
  ],
  totalCount: 4,
}
